name: dec_tl_exp
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - adwaita-icon-theme=49.0=unix_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - aom=3.9.1=hac33072_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_9
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - contourpy=1.3.3=py314h97ea11e_4
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - double-conversion=3.4.0=hecca717_0
  - epoxy=1.5.10=hb03c661_2
  - ffmpeg=8.0.1=gpl_heab3d61_711
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=pyh7db6752_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.5=h2b0a6b4_0
  - glib-tools=2.86.4=hf516916_0
  - glslang=16.2.0=h96af755_1
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gtk3=3.24.43=h993cebd_6
  - gts=0.7.6=h977cf35_4
  - harfbuzz=12.3.2=h6083320_0
  - hdf5=1.14.6=nompi_h19486de_106
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=78.2=h33c6efd_0
  - imath=3.2.2=hde8ca8f_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - jasper=4.2.8=he3c4edf_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py314h97ea11e_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.28.0=hb700be7_0
  - libabseil=20260107.1=cxx17_h7b12aa8_0
  - libaec=1.1.5=h088129d_0
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h316e467_3
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgd=2.3.3=h5fbf134_12
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.4=h6548e54_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_17
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.2=ha09017c_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopencv=4.13.0=qt6_py314h4953f36_602
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.4.1=hb56ce9e_2
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_2
  - libopenvino-auto-plugin=2025.4.1=hd85de46_2
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_2
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-ir-frontend=2025.4.1=hd41364c_2
  - libopenvino-onnx-frontend=2025.4.1=h7a07914_2
  - libopenvino-paddle-frontend=2025.4.1=h7a07914_2
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_2
  - libopenvino-tensorflow-frontend=2025.4.1=h78e8023_2
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_2
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.55=h421ea60_0
  - libpq=18.2=hb80d175_0
  - libprotobuf=6.33.5=h2b00c02_0
  - librsvg=2.60.0=h61e6d4b_1
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libsystemd0=257.10=hd0affe5_4
  - libtiff=4.7.1=h9d88235_1
  - libudev1=257.10=hd0affe5_4
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.13=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib=3.10.8=py314hdafbbf9_0
  - matplotlib-base=3.10.8=py314h1194b4b_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py314h2b28147_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.13.0=qt6_py314h976e69f_602
  - openexr=3.4.4=h40f6f1d_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.1=py314h8ec4b1a_0
  - pip=26.0.1=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - py-opencv=4.13.0=qt6_py314h07f9e98_602
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py314hf36963e_0
  - python=3.14.3=h32b2ec7_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.14=8_cp314
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.2=hb82b983_4
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=h853b02a_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.4.0=h3b84278_0
  - shaderc=2025.5=h718be3e_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2026.1=hb700be7_0
  - spot=2.14.5=py314ha160325_0
  - svt-av1=4.0.0=hecca717_0
  - tbb=2022.3.0=hb700be7_2
  - tk=8.6.13=noxft_h366c992_103
  - tornado=6.5.3=py314h5bd0f2a_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.1=py314h5bd0f2a_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.6=hecca717_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - xorg-xorgproto=2025.1=hb03c661_0
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - graphviz==0.21
      - networkx==3.6.1
      - pandas==3.0.0
      - scipy==1.17.0
prefix: /home/amin/miniforge3/envs/dec_tl_exp
